# -*- coding: utf-8 -*-
"""База продуктов для интерактивного калькулятора калорийности блюда."""

from __future__ import annotations

# kcal — калорийность на 100 г продукта
DISH_CALCULATOR_PRODUCTS: list[dict] = [
    # Мясо и пoultry
    {'id': 'chicken_breast', 'name': 'Курица (грудка)', 'kcal': 165, 'group': 'Мясо и птица'},
    {'id': 'chicken_thigh', 'name': 'Курица (бёдро)', 'kcal': 185, 'group': 'Мясо и птица'},
    {'id': 'chicken_wing', 'name': 'Курица (крылья)', 'kcal': 203, 'group': 'Мясо и птица'},
    {'id': 'turkey', 'name': 'Индейка', 'kcal': 160, 'group': 'Мясо и птица'},
    {'id': 'beef', 'name': 'Говядина', 'kcal': 250, 'group': 'Мясо и птица'},
    {'id': 'pork', 'name': 'Свинина', 'kcal': 263, 'group': 'Мясо и птица'},
    {'id': 'lamb', 'name': 'Баранина', 'kcal': 294, 'group': 'Мясо и птица'},
    {'id': 'veal', 'name': 'Телятина', 'kcal': 172, 'group': 'Мясо и птица'},
    {'id': 'liver_beef', 'name': 'Печень говяжья', 'kcal': 135, 'group': 'Мясо и птица'},
    {'id': 'minced_beef', 'name': 'Фарш говяжий', 'kcal': 254, 'group': 'Мясо и птица'},
    {'id': 'minced_pork', 'name': 'Фарш свиной', 'kcal': 315, 'group': 'Мясо и птица'},
    {'id': 'minced_mixed', 'name': 'Фарш смешанный', 'kcal': 280, 'group': 'Мясо и птица'},
    {'id': 'duck', 'name': 'Утка', 'kcal': 337, 'group': 'Мясо и птица'},
    {'id': 'rabbit', 'name': 'Кролик', 'kcal': 173, 'group': 'Мясо и птица'},
    {'id': 'bacon', 'name': 'Бекон', 'kcal': 541, 'group': 'Мясо и птица'},
    {'id': 'ham', 'name': 'Ветчина', 'kcal': 145, 'group': 'Мясо и птица'},
    {'id': 'chicken_heart', 'name': 'Куриные сердечки', 'kcal': 159, 'group': 'Мясо и птица'},
    # Колбасы
    {'id': 'sausage_doctor', 'name': 'Колбаса вареная Докторская', 'kcal': 257, 'group': 'Колбасы и сосиски'},
    {'id': 'sausage_milk', 'name': 'Колбаса вареная Молочная', 'kcal': 270, 'group': 'Колбасы и сосиски'},
    {'id': 'sausage_servelat', 'name': 'Колбаса варёно-копчёная Сервелат', 'kcal': 302, 'group': 'Колбасы и сосиски'},
    {'id': 'sausage_smoked', 'name': 'Колбаса копчёная', 'kcal': 360, 'group': 'Колбасы и сосиски'},
    {'id': 'sausage_hunting', 'name': 'Колбаса с/к Охотничьи колбаски', 'kcal': 513, 'group': 'Колбасы и сосиски'},
    {'id': 'frankfurters', 'name': 'Сосиски', 'kcal': 277, 'group': 'Колбасы и сосиски'},
    {'id': 'sausages', 'name': 'Сардельки', 'kcal': 260, 'group': 'Колбасы и сосиски'},
    {'id': 'salami', 'name': 'Салами', 'kcal': 425, 'group': 'Колбасы и сосиски'},
    # Рыба
    {'id': 'salmon', 'name': 'Лосось / сёмга', 'kcal': 208, 'group': 'Рыба и морепродукты'},
    {'id': 'trout', 'name': 'Форель', 'kcal': 119, 'group': 'Рыба и морепродукты'},
    {'id': 'cod', 'name': 'Треска', 'kcal': 78, 'group': 'Рыба и морепродукты'},
    {'id': 'herring', 'name': 'Сельдь', 'kcal': 161, 'group': 'Рыба и морепродукты'},
    {'id': 'tuna', 'name': 'Тунец', 'kcal': 144, 'group': 'Рыба и морепродукты'},
    {'id': 'carp', 'name': 'Карп', 'kcal': 112, 'group': 'Рыба и морепродукты'},
    {'id': 'shrimp', 'name': 'Креветки', 'kcal': 95, 'group': 'Рыба и морепродукты'},
    {'id': 'squid', 'name': 'Кальмар', 'kcal': 92, 'group': 'Рыба и морепродукты'},
    {'id': 'crab_sticks', 'name': 'Крабные палочки', 'kcal': 95, 'group': 'Рыба и морепродукты'},
    {'id': 'mackerel', 'name': 'Скумбрия', 'kcal': 205, 'group': 'Рыба и морепродукты'},
    {'id': 'pike', 'name': 'Щука', 'kcal': 84, 'group': 'Рыба и морепродукты'},
    {'id': 'hake', 'name': 'Хек', 'kcal': 86, 'group': 'Рыба и морепродукты'},
    {'id': 'pollock', 'name': 'Минтай', 'kcal': 72, 'group': 'Рыба и морепродукты'},
    {'id': 'mussels', 'name': 'Мидии', 'kcal': 77, 'group': 'Рыба и морепродукты'},
    {'id': 'octopus', 'name': 'Осьминог', 'kcal': 82, 'group': 'Рыба и морепродукты'},
    # Молочные
    {'id': 'milk_25', 'name': 'Молоко 2,5%', 'kcal': 52, 'group': 'Молочные продукты'},
    {'id': 'milk_32', 'name': 'Молоко 3,2%', 'kcal': 60, 'group': 'Молочные продукты'},
    {'id': 'kefir', 'name': 'Кефир 2,5%', 'kcal': 50, 'group': 'Молочные продукты'},
    {'id': 'yogurt_natural', 'name': 'Йогурт натуральный', 'kcal': 66, 'group': 'Молочные продукты'},
    {'id': 'cottage_5', 'name': 'Творог 5%', 'kcal': 121, 'group': 'Молочные продукты'},
    {'id': 'cottage_9', 'name': 'Творог 9%', 'kcal': 159, 'group': 'Молочные продукты'},
    {'id': 'sour_cream_20', 'name': 'Сметана 20%', 'kcal': 206, 'group': 'Молочные продукты'},
    {'id': 'sour_cream_15', 'name': 'Сметана 15%', 'kcal': 158, 'group': 'Молочные продукты'},
    {'id': 'cheese_hard', 'name': 'Сыр твёрдый', 'kcal': 356, 'group': 'Молочные продукты'},
    {'id': 'cheese_mozzarella', 'name': 'Сыр Моцарелла', 'kcal': 280, 'group': 'Молочные продукты'},
    {'id': 'cheese_feta', 'name': 'Сыр Фета', 'kcal': 264, 'group': 'Молочные продукты'},
    {'id': 'butter', 'name': 'Масло сливочное', 'kcal': 748, 'group': 'Молочные продукты'},
    {'id': 'cream_33', 'name': 'Сливки 33%', 'kcal': 322, 'group': 'Молочные продукты'},
    {'id': 'milk_10', 'name': 'Молоко 1%', 'kcal': 42, 'group': 'Молочные продукты'},
    {'id': 'milk_05', 'name': 'Молоко обезжиренное', 'kcal': 34, 'group': 'Молочные продукты'},
    {'id': 'ryazhenka', 'name': 'Ряженка', 'kcal': 54, 'group': 'Молочные продукты'},
    {'id': 'condensed_milk', 'name': 'Сгущённое молоко', 'kcal': 320, 'group': 'Молочные продукты'},
    {'id': 'cheese_cream', 'name': 'Сыр сливочный', 'kcal': 342, 'group': 'Молочные продукты'},
    {'id': 'cheese_parmesan', 'name': 'Сыр Пармезан', 'kcal': 392, 'group': 'Молочные продукты'},
    {'id': 'cheese_cottage', 'name': 'Сыр адыгейский', 'kcal': 240, 'group': 'Молочные продукты'},
    {'id': 'cheese_processed', 'name': 'Сыр плавленый', 'kcal': 290, 'group': 'Молочные продукты'},
    # Яйца
    {'id': 'egg', 'name': 'Яйцо куриное', 'kcal': 157, 'group': 'Яйца'},
    {'id': 'egg_white', 'name': 'Белок яичный', 'kcal': 52, 'group': 'Яйца'},
    {'id': 'egg_yolk', 'name': 'Желток яичный', 'kcal': 352, 'group': 'Яйца'},
    # Крупы и макароны
    {'id': 'rice_white', 'name': 'Рис белый (варёный)', 'kcal': 130, 'group': 'Крупы и макароны'},
    {'id': 'rice_brown', 'name': 'Рис бурый (варёный)', 'kcal': 111, 'group': 'Крупы и макароны'},
    {'id': 'buckwheat', 'name': 'Гречка (варёная)', 'kcal': 132, 'group': 'Крупы и макароны'},
    {'id': 'oatmeal', 'name': 'Овсянка (варёная)', 'kcal': 88, 'group': 'Крупы и макароны'},
    {'id': 'millet', 'name': 'Пшено (варёное)', 'kcal': 119, 'group': 'Крупы и макароны'},
    {'id': 'pasta', 'name': 'Макароны (варёные)', 'kcal': 131, 'group': 'Крупы и макароны'},
    {'id': 'bulgur', 'name': 'Булгур (варёный)', 'kcal': 83, 'group': 'Крупы и макароны'},
    {'id': 'quinoa', 'name': 'Киноа (варёная)', 'kcal': 120, 'group': 'Крупы и макароны'},
    {'id': 'rice_dry', 'name': 'Рис (сухой)', 'kcal': 344, 'group': 'Крупы и макароны'},
    {'id': 'buckwheat_dry', 'name': 'Гречка (сухая)', 'kcal': 313, 'group': 'Крупы и макароны'},
    {'id': 'pasta_dry', 'name': 'Макароны (сухие)', 'kcal': 344, 'group': 'Крупы и макароны'},
    {'id': 'semolina_dry', 'name': 'Манка (сухая)', 'kcal': 328, 'group': 'Крупы и макароны'},
    {'id': 'semolina', 'name': 'Манная каша (варёная)', 'kcal': 98, 'group': 'Крупы и макароны'},
    {'id': 'barley_dry', 'name': 'Перловка (сухая)', 'kcal': 315, 'group': 'Крупы и макароны'},
    {'id': 'barley', 'name': 'Перловка (варёная)', 'kcal': 123, 'group': 'Крупы и макароны'},
    {'id': 'pearl_barley_dry', 'name': 'Ячневая крупа (сухая)', 'kcal': 324, 'group': 'Крупы и макароны'},
    {'id': 'corn_flakes', 'name': 'Кукурузные хлопья', 'kcal': 357, 'group': 'Крупы и макароны'},
    {'id': 'couscous', 'name': 'Кускус (варёный)', 'kcal': 112, 'group': 'Крупы и макароны'},
    # Хлеб
    {'id': 'bread_white', 'name': 'Хлеб белый', 'kcal': 265, 'group': 'Хлеб и выпечка'},
    {'id': 'bread_rye', 'name': 'Хлеб ржаной', 'kcal': 259, 'group': 'Хлеб и выпечка'},
    {'id': 'bread_whole', 'name': 'Хлеб цельнозерновой', 'kcal': 247, 'group': 'Хлеб и выпечка'},
    {'id': 'lavash', 'name': 'Лаваш', 'kcal': 275, 'group': 'Хлеб и выпечка'},
    {'id': 'crispbread', 'name': 'Хлебцы', 'kcal': 310, 'group': 'Хлеб и выпечка'},
    {'id': 'bun', 'name': 'Булочка', 'kcal': 280, 'group': 'Хлеб и выпечка'},
    {'id': 'pancake', 'name': 'Блин', 'kcal': 227, 'group': 'Хлеб и выпечка'},
    {'id': 'baguette', 'name': 'Багет', 'kcal': 262, 'group': 'Хлеб и выпечка'},
    {'id': 'pita', 'name': 'Пита', 'kcal': 275, 'group': 'Хлеб и выпечка'},
    {'id': 'croissant', 'name': 'Круассан', 'kcal': 406, 'group': 'Хлеб и выпечка'},
    {'id': 'muffin', 'name': 'Кекс', 'kcal': 375, 'group': 'Хлеб и выпечка'},
    # Овощи
    {'id': 'potato', 'name': 'Картофель', 'kcal': 80, 'group': 'Овощи'},
    {'id': 'potato_boiled', 'name': 'Картофель (варёный)', 'kcal': 82, 'group': 'Овощи'},
    {'id': 'carrot', 'name': 'Морковь', 'kcal': 41, 'group': 'Овощи'},
    {'id': 'beet', 'name': 'Свёкла', 'kcal': 43, 'group': 'Овощи'},
    {'id': 'cabbage', 'name': 'Капуста белокочанная', 'kcal': 27, 'group': 'Овощи'},
    {'id': 'cabbage_red', 'name': 'Капуста краснокочанная', 'kcal': 31, 'group': 'Овощи'},
    {'id': 'onion', 'name': 'Лук репчатый', 'kcal': 41, 'group': 'Овощи'},
    {'id': 'garlic', 'name': 'Чеснок', 'kcal': 149, 'group': 'Овощи'},
    {'id': 'cucumber', 'name': 'Огурец', 'kcal': 15, 'group': 'Овощи'},
    {'id': 'tomato', 'name': 'Помидор', 'kcal': 20, 'group': 'Овощи'},
    {'id': 'pepper', 'name': 'Перец болгарский', 'kcal': 27, 'group': 'Овощи'},
    {'id': 'zucchini', 'name': 'Кабачок', 'kcal': 24, 'group': 'Овощи'},
    {'id': 'eggplant', 'name': 'Баклажан', 'kcal': 24, 'group': 'Овощи'},
    {'id': 'pumpkin', 'name': 'Тыква', 'kcal': 28, 'group': 'Овощи'},
    {'id': 'broccoli', 'name': 'Брокколи', 'kcal': 34, 'group': 'Овощи'},
    {'id': 'cauliflower', 'name': 'Цветная капуста', 'kcal': 30, 'group': 'Овощи'},
    {'id': 'spinach', 'name': 'Шпинат', 'kcal': 23, 'group': 'Овощи'},
    {'id': 'green_peas', 'name': 'Горошек зелёный', 'kcal': 81, 'group': 'Овощи'},
    {'id': 'corn', 'name': 'Кукуруза', 'kcal': 96, 'group': 'Овощи'},
    {'id': 'mushrooms', 'name': 'Грибы (шампиньоны)', 'kcal': 27, 'group': 'Овощи'},
    {'id': 'celery', 'name': 'Сельдерей', 'kcal': 16, 'group': 'Овощи'},
    {'id': 'radish', 'name': 'Редис', 'kcal': 20, 'group': 'Овощи'},
    {'id': 'lettuce', 'name': 'Салат листовой', 'kcal': 15, 'group': 'Овощи'},
    {'id': 'green_onion', 'name': 'Лук зелёный', 'kcal': 32, 'group': 'Овощи'},
    {'id': 'dill', 'name': 'Укроп', 'kcal': 40, 'group': 'Овощи'},
    {'id': 'parsley', 'name': 'Петрушка', 'kcal': 49, 'group': 'Овощи'},
    {'id': 'sauerkraut', 'name': 'Капуста квашеная', 'kcal': 19, 'group': 'Овощи'},
    {'id': 'pickles', 'name': 'Огурцы солёные', 'kcal': 11, 'group': 'Овощи'},
    {'id': 'tomato_cherry', 'name': 'Помидоры черри', 'kcal': 18, 'group': 'Овощи'},
    {'id': 'asparagus', 'name': 'Спаржа', 'kcal': 20, 'group': 'Овощи'},
    {'id': 'leek', 'name': 'Лук-порей', 'kcal': 61, 'group': 'Овощи'},
    # Фрукты
    {'id': 'apple', 'name': 'Яблоко', 'kcal': 52, 'group': 'Фрукты и ягоды'},
    {'id': 'banana', 'name': 'Банан', 'kcal': 89, 'group': 'Фрукты и ягоды'},
    {'id': 'orange', 'name': 'Апельсин', 'kcal': 47, 'group': 'Фрукты и ягоды'},
    {'id': 'mandarin', 'name': 'Мандарин', 'kcal': 53, 'group': 'Фрукты и ягоды'},
    {'id': 'pear', 'name': 'Груша', 'kcal': 57, 'group': 'Фрукты и ягоды'},
    {'id': 'grape', 'name': 'Виноград', 'kcal': 69, 'group': 'Фрукты и ягоды'},
    {'id': 'strawberry', 'name': 'Клубника', 'kcal': 32, 'group': 'Фрукты и ягоды'},
    {'id': 'blueberry', 'name': 'Черника', 'kcal': 57, 'group': 'Фрукты и ягоды'},
    {'id': 'watermelon', 'name': 'Арбуз', 'kcal': 30, 'group': 'Фрукты и ягоды'},
    {'id': 'melon', 'name': 'Дыня', 'kcal': 35, 'group': 'Фрукты и ягоды'},
    {'id': 'kiwi', 'name': 'Киви', 'kcal': 61, 'group': 'Фрукты и ягоды'},
    {'id': 'lemon', 'name': 'Лимон', 'kcal': 29, 'group': 'Фрукты и ягоды'},
    {'id': 'avocado', 'name': 'Авокадо', 'kcal': 160, 'group': 'Фрукты и ягоды'},
    {'id': 'dried_apricot', 'name': 'Курага', 'kcal': 241, 'group': 'Фрукты и ягоды'},
    {'id': 'raisin', 'name': 'Изюм', 'kcal': 299, 'group': 'Фрукты и ягоды'},
    {'id': 'cherry', 'name': 'Вишня', 'kcal': 52, 'group': 'Фрукты и ягоды'},
    {'id': 'plum', 'name': 'Слива', 'kcal': 46, 'group': 'Фрукты и ягоды'},
    {'id': 'peach', 'name': 'Персик', 'kcal': 39, 'group': 'Фрукты и ягоды'},
    {'id': 'apricot', 'name': 'Абрикос', 'kcal': 48, 'group': 'Фрукты и ягоды'},
    {'id': 'pineapple', 'name': 'Ананас', 'kcal': 50, 'group': 'Фрукты и ягоды'},
    {'id': 'mango', 'name': 'Манго', 'kcal': 60, 'group': 'Фрукты и ягоды'},
    {'id': 'cranberry', 'name': 'Клюква', 'kcal': 46, 'group': 'Фрукты и ягоды'},
    {'id': 'raspberry', 'name': 'Малина', 'kcal': 52, 'group': 'Фрукты и ягоды'},
    {'id': 'currant', 'name': 'Смородина', 'kcal': 44, 'group': 'Фрукты и ягоды'},
    {'id': 'prunes', 'name': 'Чернослив', 'kcal': 256, 'group': 'Фрукты и ягоды'},
    {'id': 'dates', 'name': 'Финики', 'kcal': 282, 'group': 'Фрукты и ягоды'},
    # Орехи и семена
    {'id': 'walnut', 'name': 'Грецкий орех', 'kcal': 654, 'group': 'Орехи и семена'},
    {'id': 'almond', 'name': 'Миндаль', 'kcal': 579, 'group': 'Орехи и семена'},
    {'id': 'peanut', 'name': 'Арахис', 'kcal': 567, 'group': 'Орехи и семена'},
    {'id': 'sunflower_seeds', 'name': 'Семечки подсолнечника', 'kcal': 578, 'group': 'Орехи и семена'},
    {'id': 'pumpkin_seeds', 'name': 'Семечки тыквы', 'kcal': 559, 'group': 'Орехи и семена'},
    {'id': 'cashew', 'name': 'Кешью', 'kcal': 553, 'group': 'Орехи и семена'},
    {'id': 'hazelnut', 'name': 'Фундук', 'kcal': 628, 'group': 'Орехи и семена'},
    {'id': 'pistachio', 'name': 'Фисташки', 'kcal': 556, 'group': 'Орехи и семена'},
    {'id': 'pine_nuts', 'name': 'Кедровые орехи', 'kcal': 673, 'group': 'Орехи и семена'},
    {'id': 'sesame', 'name': 'Кунжут', 'kcal': 565, 'group': 'Орехи и семена'},
    {'id': 'chia', 'name': 'Семена чиа', 'kcal': 486, 'group': 'Орехи и семена'},
    # Масла и соусы
    {'id': 'sunflower_oil', 'name': 'Масло подсолнечное', 'kcal': 899, 'group': 'Масла и соусы'},
    {'id': 'olive_oil', 'name': 'Масло оливковое', 'kcal': 884, 'group': 'Масла и соусы'},
    {'id': 'mayo_67', 'name': 'Майонез 67%', 'kcal': 624, 'group': 'Масла и соусы'},
    {'id': 'mayo_light', 'name': 'Майонез лёгкий', 'kcal': 260, 'group': 'Масла и соусы'},
    {'id': 'ketchup', 'name': 'Кетчуп', 'kcal': 112, 'group': 'Масла и соусы'},
    {'id': 'mustard', 'name': 'Горчица', 'kcal': 162, 'group': 'Масла и соусы'},
    {'id': 'soy_sauce', 'name': 'Соевый соус', 'kcal': 53, 'group': 'Масла и соусы'},
    {'id': 'tomato_paste', 'name': 'Томатная паста', 'kcal': 82, 'group': 'Масла и соусы'},
    {'id': 'sour_cream_sauce', 'name': 'Сметанный соус', 'kcal': 190, 'group': 'Масла и соусы'},
    {'id': 'linseed_oil', 'name': 'Масло льняное', 'kcal': 884, 'group': 'Масла и соусы'},
    {'id': 'coconut_oil', 'name': 'Масло кокосовое', 'kcal': 862, 'group': 'Масла и соусы'},
    {'id': 'vinegar', 'name': 'Уксус', 'kcal': 19, 'group': 'Масла и соусы'},
    {'id': 'horseradish', 'name': 'Хрен', 'kcal': 48, 'group': 'Масла и соусы'},
    {'id': 'adjika', 'name': 'Аджика', 'kcal': 59, 'group': 'Масла и соусы'},
    {'id': 'bbq_sauce', 'name': 'Соус барбекю', 'kcal': 165, 'group': 'Масла и соусы'},
    # Бобовые
    {'id': 'beans', 'name': 'Фасоль (варёная)', 'kcal': 127, 'group': 'Бобовые'},
    {'id': 'chickpeas', 'name': 'Нут (варёный)', 'kcal': 164, 'group': 'Бобовые'},
    {'id': 'lentils', 'name': 'Чечевица (варёная)', 'kcal': 116, 'group': 'Бобовые'},
    {'id': 'peas_dry', 'name': 'Горох (варёный)', 'kcal': 118, 'group': 'Бобовые'},
    {'id': 'beans_dry', 'name': 'Фасоль (сухая)', 'kcal': 298, 'group': 'Бобовые'},
    {'id': 'chickpeas_dry', 'name': 'Нут (сухой)', 'kcal': 364, 'group': 'Бобовые'},
    {'id': 'lentils_dry', 'name': 'Чечевица (сухая)', 'kcal': 295, 'group': 'Бобовые'},
    {'id': 'soy_tofu', 'name': 'Тофу', 'kcal': 76, 'group': 'Бобовые'},
    {'id': 'edamame', 'name': 'Эдамаме', 'kcal': 122, 'group': 'Бобовые'},
    # Сладости
    {'id': 'sugar', 'name': 'Сахар', 'kcal': 398, 'group': 'Сладости'},
    {'id': 'honey', 'name': 'Мёд', 'kcal': 304, 'group': 'Сладости'},
    {'id': 'chocolate_dark', 'name': 'Шоколад тёмный', 'kcal': 546, 'group': 'Сладости'},
    {'id': 'chocolate_milk', 'name': 'Шоколад молочный', 'kcal': 535, 'group': 'Сладости'},
    {'id': 'cookie', 'name': 'Печенье', 'kcal': 417, 'group': 'Сладости'},
    {'id': 'cake', 'name': 'Торт', 'kcal': 350, 'group': 'Сладости'},
    {'id': 'ice_cream', 'name': 'Мороженое', 'kcal': 207, 'group': 'Сладости'},
    {'id': 'jam', 'name': 'Варенье', 'kcal': 263, 'group': 'Сладости'},
    {'id': 'marshmallow', 'name': 'Зефир', 'kcal': 304, 'group': 'Сладости'},
    {'id': 'halva', 'name': 'Халва', 'kcal': 516, 'group': 'Сладости'},
    {'id': 'waffle', 'name': 'Вафли', 'kcal': 425, 'group': 'Сладости'},
    {'id': 'caramel', 'name': 'Карамель', 'kcal': 382, 'group': 'Сладости'},
    # Напитки
    {'id': 'water', 'name': 'Вода', 'kcal': 0, 'group': 'Напитки'},
    {'id': 'juice_apple', 'name': 'Сок яблочный', 'kcal': 46, 'group': 'Напитки'},
    {'id': 'juice_orange', 'name': 'Сок апельсиновый', 'kcal': 45, 'group': 'Напитки'},
    {'id': 'cola', 'name': 'Кола', 'kcal': 42, 'group': 'Напитки'},
    {'id': 'coffee_black', 'name': 'Кофе чёрный (без сахара)', 'kcal': 2, 'group': 'Напитки'},
    {'id': 'tea', 'name': 'Чай (без сахара)', 'kcal': 1, 'group': 'Напитки'},
    {'id': 'kvass', 'name': 'Квас', 'kcal': 27, 'group': 'Напитки'},
    {'id': 'compote', 'name': 'Компот из сухофруктов', 'kcal': 60, 'group': 'Напитки'},
    {'id': 'cocoa', 'name': 'Какао на молоке', 'kcal': 77, 'group': 'Напитки'},
    {'id': 'lemonade', 'name': 'Лимонад', 'kcal': 40, 'group': 'Напитки'},
    {'id': 'mineral_water', 'name': 'Минеральная вода', 'kcal': 0, 'group': 'Напитки'},
    # Прочее
    {'id': 'salt', 'name': 'Соль', 'kcal': 0, 'group': 'Прочее'},
    {'id': 'flour_wheat', 'name': 'Мука пшеничная', 'kcal': 334, 'group': 'Прочее'},
    {'id': 'flour_rye', 'name': 'Мука ржаная', 'kcal': 298, 'group': 'Прочее'},
    {'id': 'yeast_dry', 'name': 'Дрожжи сухие', 'kcal': 105, 'group': 'Прочее'},
    {'id': 'baking_powder', 'name': 'Разрыхлитель', 'kcal': 53, 'group': 'Прочее'},
    {'id': 'cocoa_powder', 'name': 'Какао-порошок', 'kcal': 228, 'group': 'Прочее'},
    {'id': 'vanilla_sugar', 'name': 'Ванильный сахар', 'kcal': 395, 'group': 'Прочее'},
    {'id': 'gelatin', 'name': 'Желатин', 'kcal': 355, 'group': 'Прочее'},
    {'id': 'breadcrumbs', 'name': 'Сухари панировочные', 'kcal': 395, 'group': 'Прочее'},
    {'id': 'starch', 'name': 'Крахмал картофельный', 'kcal': 357, 'group': 'Прочее'},
    {'id': 'poppy_seeds', 'name': 'Мак', 'kcal': 525, 'group': 'Прочее'},
    {'id': 'basil_dried', 'name': 'Базилик сушёный', 'kcal': 233, 'group': 'Прочее'},
    {'id': 'pepper_black', 'name': 'Перец чёрный молотый', 'kcal': 251, 'group': 'Прочее'},
    {'id': 'paprika', 'name': 'Паприка', 'kcal': 282, 'group': 'Прочее'},
    {'id': 'cinnamon', 'name': 'Корица', 'kcal': 247, 'group': 'Прочее'},
    # Дополнительно — мясо и птица
    {'id': 'goose', 'name': 'Гусь', 'kcal': 305, 'group': 'Мясо и птица'},
    {'id': 'quail', 'name': 'Перепёлка', 'kcal': 192, 'group': 'Мясо и птица'},
    {'id': 'tongue_beef', 'name': 'Язык говяжий', 'kcal': 224, 'group': 'Мясо и птица'},
    {'id': 'kidney_beef', 'name': 'Почки говяжьи', 'kcal': 86, 'group': 'Мясо и птица'},
    {'id': 'chicken_liver', 'name': 'Печень куриная', 'kcal': 136, 'group': 'Мясо и птица'},
    {'id': 'meatballs', 'name': 'Фрикадельки', 'kcal': 220, 'group': 'Мясо и птица'},
    # Дополнительно — рыба
    {'id': 'bream', 'name': 'Лещ', 'kcal': 105, 'group': 'Рыба и морепродукты'},
    {'id': 'perch', 'name': 'Окунь', 'kcal': 91, 'group': 'Рыба и морепродукты'},
    {'id': 'flounder', 'name': 'Камбала', 'kcal': 90, 'group': 'Рыба и морепродукты'},
    {'id': 'sardine', 'name': 'Сардина', 'kcal': 185, 'group': 'Рыба и морепродукты'},
    {'id': 'caviar_red', 'name': 'Икра красная', 'kcal': 252, 'group': 'Рыба и морепродукты'},
    {'id': 'seaweed', 'name': 'Морская капуста', 'kcal': 49, 'group': 'Рыба и морепродукты'},
    {'id': 'scallops', 'name': 'Гребешки', 'kcal': 88, 'group': 'Рыба и морепродукты'},
    # Дополнительно — молочные
    {'id': 'milk_40', 'name': 'Молоко 4%', 'kcal': 67, 'group': 'Молочные продукты'},
    {'id': 'cottage_0', 'name': 'Творог обезжиренный', 'kcal': 88, 'group': 'Молочные продукты'},
    {'id': 'ricotta', 'name': 'Рикотта', 'kcal': 174, 'group': 'Молочные продукты'},
    {'id': 'mascarpone', 'name': 'Маскарпоне', 'kcal': 429, 'group': 'Молочные продукты'},
    {'id': 'yogurt_greek', 'name': 'Йогурт греческий', 'kcal': 97, 'group': 'Молочные продукты'},
    {'id': 'yogurt_fruit', 'name': 'Йогурт фруктовый', 'kcal': 105, 'group': 'Молочные продукты'},
    {'id': 'cheese_blue', 'name': 'Сыр с плесенью', 'kcal': 353, 'group': 'Молочные продукты'},
    {'id': 'cheese_suluguni', 'name': 'Сыр Сулугуни', 'kcal': 286, 'group': 'Молочные продукты'},
    {'id': 'cheese_bryndza', 'name': 'Брынза', 'kcal': 260, 'group': 'Молочные продукты'},
    {'id': 'cream_10', 'name': 'Сливки 10%', 'kcal': 119, 'group': 'Молочные продукты'},
    {'id': 'cream_20', 'name': 'Сливки 20%', 'kcal': 205, 'group': 'Молочные продукты'},
    # Дополнительно — крупы
    {'id': 'pearl_barley', 'name': 'Ячневая крупа (варёная)', 'kcal': 124, 'group': 'Крупы и макароны'},
    {'id': 'amaranth', 'name': 'Амарант (варёный)', 'kcal': 102, 'group': 'Крупы и макароны'},
    {'id': 'spelt', 'name': 'Полба (варёная)', 'kcal': 127, 'group': 'Крупы и макароны'},
    {'id': 'rice_black', 'name': 'Рис чёрный (варёный)', 'kcal': 143, 'group': 'Крупы и макароны'},
    {'id': 'noodles_egg', 'name': 'Лапша яичная (сухая)', 'kcal': 384, 'group': 'Крупы и макароны'},
    {'id': 'vermicelli', 'name': 'Вермишель (сухая)', 'kcal': 342, 'group': 'Крупы и макароны'},
    # Дополнительно — хлеб
    {'id': 'tortilla', 'name': 'Тортилья', 'kcal': 237, 'group': 'Хлеб и выпечка'},
    {'id': 'pie_sweet', 'name': 'Пирог сладкий', 'kcal': 340, 'group': 'Хлеб и выпечка'},
    {'id': 'donut', 'name': 'Пончик', 'kcal': 452, 'group': 'Хлеб и выпечка'},
    {'id': 'eclair', 'name': 'Эклер', 'kcal': 262, 'group': 'Хлеб и выпечка'},
    {'id': 'gingerbread', 'name': 'Пряник', 'kcal': 350, 'group': 'Хлеб и выпечка'},
    # Дополнительно — овощи
    {'id': 'turnip', 'name': 'Репа', 'kcal': 30, 'group': 'Овощи'},
    {'id': 'kohlrabi', 'name': 'Кольраби', 'kcal': 27, 'group': 'Овощи'},
    {'id': 'rutabaga', 'name': 'Брюква', 'kcal': 37, 'group': 'Овощи'},
    {'id': 'ginger_root', 'name': 'Имбирь корень', 'kcal': 80, 'group': 'Овощи'},
    {'id': 'chili', 'name': 'Перец чили', 'kcal': 40, 'group': 'Овощи'},
    {'id': 'artichoke', 'name': 'Артишок', 'kcal': 47, 'group': 'Овощи'},
    {'id': 'beans_green', 'name': 'Фасоль стручковая', 'kcal': 31, 'group': 'Овощи'},
    {'id': 'okra', 'name': 'Бамия', 'kcal': 33, 'group': 'Овощи'},
    {'id': 'daikon', 'name': 'Редька дайкон', 'kcal': 21, 'group': 'Овощи'},
    {'id': 'basil_fresh', 'name': 'Базилик свежий', 'kcal': 23, 'group': 'Овощи'},
    {'id': 'cilantro', 'name': 'Кинза', 'kcal': 23, 'group': 'Овощи'},
    # Дополнительно — фрукты
    {'id': 'pomegranate', 'name': 'Гранат', 'kcal': 83, 'group': 'Фрукты и ягоды'},
    {'id': 'fig', 'name': 'Инжир', 'kcal': 74, 'group': 'Фрукты и ягоды'},
    {'id': 'papaya', 'name': 'Папайя', 'kcal': 43, 'group': 'Фрукты и ягоды'},
    {'id': 'coconut', 'name': 'Кокос', 'kcal': 354, 'group': 'Фрукты и ягоды'},
    {'id': 'lime', 'name': 'Лайм', 'kcal': 30, 'group': 'Фрукты и ягоды'},
    {'id': 'grapefruit', 'name': 'Грейпфрут', 'kcal': 42, 'group': 'Фрукты и ягоды'},
    {'id': 'pomelo', 'name': 'Помело', 'kcal': 38, 'group': 'Фрукты и ягоды'},
    {'id': 'gooseberry', 'name': 'Крыжовник', 'kcal': 44, 'group': 'Фрукты и ягоды'},
    {'id': 'blackberry', 'name': 'Ежевика', 'kcal': 43, 'group': 'Фрукты и ягоды'},
    {'id': 'dried_figs', 'name': 'Инжир сушёный', 'kcal': 249, 'group': 'Фрукты и ягоды'},
    # Дополнительно — соусы и напитки
    {'id': 'pesto', 'name': 'Соус песто', 'kcal': 426, 'group': 'Масла и соусы'},
    {'id': 'tkemali', 'name': 'Соус ткемали', 'kcal': 45, 'group': 'Масла и соусы'},
    {'id': 'teriyaki', 'name': 'Соус терияки', 'kcal': 89, 'group': 'Масла и соусы'},
    {'id': 'soy_milk', 'name': 'Соевое молоко', 'kcal': 54, 'group': 'Напитки'},
    {'id': 'smoothie', 'name': 'Смузи фруктовый', 'kcal': 65, 'group': 'Напитки'},
    {'id': 'mors', 'name': 'Морс ягодный', 'kcal': 41, 'group': 'Напитки'},
    {'id': 'kissel', 'name': 'Кисель', 'kcal': 53, 'group': 'Напитки'},
    # Дополнительно — сладости
    {'id': 'chocolate_white', 'name': 'Шоколад белый', 'kcal': 539, 'group': 'Сладости'},
    {'id': 'pastila', 'name': 'Пастила', 'kcal': 310, 'group': 'Сладости'},
    {'id': 'biscuit', 'name': 'Бисквит', 'kcal': 400, 'group': 'Сладости'},
    {'id': 'brownie', 'name': 'Брауни', 'kcal': 405, 'group': 'Сладости'},
    {'id': 'minced_chicken', 'name': 'Фарш куриный', 'kcal': 189, 'group': 'Мясо и птица'},
    {'id': 'chicken_drumstick', 'name': 'Куриная голень', 'kcal': 190, 'group': 'Мясо и птица'},
    {'id': 'chicken_leg', 'name': 'Куриное бедро', 'kcal': 185, 'group': 'Мясо и птица'},
    {'id': 'turkey_breast', 'name': 'Индейка (филе грудки)', 'kcal': 135, 'group': 'Мясо и птица'},
    {'id': 'beef_steak', 'name': 'Говяжий стейк', 'kcal': 271, 'group': 'Мясо и птица'},
    {'id': 'beef_stew', 'name': 'Говядина для тушения', 'kcal': 230, 'group': 'Мясо и птица'},
    {'id': 'beef_brisket', 'name': 'Говяжья грудинка', 'kcal': 280, 'group': 'Мясо и птица'},
    {'id': 'pork_neck', 'name': 'Свиная шея', 'kcal': 276, 'group': 'Мясо и птица'},
    {'id': 'pork_ribs', 'name': 'Свиные рёбрышки', 'kcal': 321, 'group': 'Мясо и птица'},
    {'id': 'pork_belly', 'name': 'Свиная грудинка', 'kcal': 518, 'group': 'Мясо и птица'},
    {'id': 'pork_loin', 'name': 'Свиная вырезка', 'kcal': 143, 'group': 'Мясо и птица'},
    {'id': 'lamb_shoulder', 'name': 'Баранина (лопатка)', 'kcal': 282, 'group': 'Мясо и птица'},
    {'id': 'lard_salted', 'name': 'Сало солёное', 'kcal': 797, 'group': 'Мясо и птица'},
    {'id': 'smoked_ribs', 'name': 'Рёбрышки копчёные', 'kcal': 340, 'group': 'Мясо и птица'},
    {'id': 'chicken_stomach', 'name': 'Куриные желудки', 'kcal': 94, 'group': 'Мясо и птица'},
    {'id': 'beef_lung', 'name': 'Лёгкое говяжье', 'kcal': 92, 'group': 'Мясо и птица'},
    {'id': 'chicken_nuggets', 'name': 'Куриные наггетсы', 'kcal': 296, 'group': 'Мясо и птица'},
    {'id': 'sausage_russian', 'name': 'Колбаса вареная Русская', 'kcal': 302, 'group': 'Колбасы и сосиски'},
    {'id': 'sausage_krakov', 'name': 'Колбаса вареная Краковская', 'kcal': 290, 'group': 'Колбасы и сосиски'},
    {'id': 'sausage_amateur', 'name': 'Колбаса вареная Любительская', 'kcal': 301, 'group': 'Колбасы и сосиски'},
    {'id': 'ham_chicken', 'name': 'Ветчина куриная', 'kcal': 110, 'group': 'Колбасы и сосиски'},
    {'id': 'hot_dog', 'name': 'Сосиски для hot-dog', 'kcal': 280, 'group': 'Колбасы и сосиски'},
    {'id': 'sausage_grill', 'name': 'Колбаски для гриля', 'kcal': 290, 'group': 'Колбасы и сосиски'},
    {'id': 'sausage_cervelat', 'name': 'Колбаса сырокопчёная', 'kcal': 490, 'group': 'Колбасы и сосиски'},
    {'id': 'herring_salted', 'name': 'Сельдь солёная', 'kcal': 217, 'group': 'Рыба и морепродукты'},
    {'id': 'salmon_salted', 'name': 'Сёмга слабосолёная', 'kcal': 202, 'group': 'Рыба и морепродукты'},
    {'id': 'trout_smoked', 'name': 'Форель копчёная', 'kcal': 162, 'group': 'Рыба и морепродукты'},
    {'id': 'chum_salmon', 'name': 'Кета', 'kcal': 138, 'group': 'Рыба и морепродукты'},
    {'id': 'pink_salmon', 'name': 'Горбуша', 'kcal': 140, 'group': 'Рыба и морепродукты'},
    {'id': 'zander', 'name': 'Судак', 'kcal': 84, 'group': 'Рыба и морепродукты'},
    {'id': 'navaga', 'name': 'Навага', 'kcal': 73, 'group': 'Рыба и морепродукты'},
    {'id': 'capelin', 'name': 'Мойва', 'kcal': 157, 'group': 'Рыба и морепродукты'},
    {'id': 'smelt', 'name': 'Корюшка', 'kcal': 124, 'group': 'Рыба и морепродукты'},
    {'id': 'tuna_canned', 'name': 'Тунец консервированный', 'kcal': 198, 'group': 'Рыба и морепродукты'},
    {'id': 'saury_canned', 'name': 'Сайра консервированная', 'kcal': 205, 'group': 'Рыба и морепродукты'},
    {'id': 'caviar_capelin', 'name': 'Икра минтая', 'kcal': 252, 'group': 'Рыба и морепродукты'},
    {'id': 'squid_canned', 'name': 'Кальмар консервированный', 'kcal': 110, 'group': 'Рыба и морепродукты'},
    {'id': 'fish_fillet_pollock', 'name': 'Филе минтая', 'kcal': 72, 'group': 'Рыба и морепродукты'},
    {'id': 'kefir_1', 'name': 'Кефир 1%', 'kcal': 40, 'group': 'Молочные продукты'},
    {'id': 'kefir_32', 'name': 'Кефир 3,2%', 'kcal': 56, 'group': 'Молочные продукты'},
    {'id': 'sour_milk', 'name': 'Простокваша', 'kcal': 58, 'group': 'Молочные продукты'},
    {'id': 'baked_milk', 'name': 'Топлёное молоко', 'kcal': 67, 'group': 'Молочные продукты'},
    {'id': 'cottage_2', 'name': 'Творог 2%', 'kcal': 103, 'group': 'Молочные продукты'},
    {'id': 'cottage_18', 'name': 'Творог 18%', 'kcal': 232, 'group': 'Молочные продукты'},
    {'id': 'cheese_russian', 'name': 'Сыр Российский', 'kcal': 364, 'group': 'Молочные продукты'},
    {'id': 'cheese_gouda', 'name': 'Сыр Голландский', 'kcal': 356, 'group': 'Молочные продукты'},
    {'id': 'cheese_emmental', 'name': 'Сыр Эмменталь', 'kcal': 380, 'group': 'Молочные продукты'},
    {'id': 'cheese_cheddar', 'name': 'Сыр Чеддер', 'kcal': 392, 'group': 'Молочные продукты'},
    {'id': 'margarine', 'name': 'Маргарин', 'kcal': 743, 'group': 'Молочные продукты'},
    {'id': 'sour_cream_30', 'name': 'Сметана 30%', 'kcal': 337, 'group': 'Молочные продукты'},
    {'id': 'yogurt_drink', 'name': 'Йогурт питьевой', 'kcal': 72, 'group': 'Молочные продукты'},
    {'id': 'milk_uht', 'name': 'Молоко UHT 2,5%', 'kcal': 53, 'group': 'Молочные продукты'},
    {'id': 'cream_cheese_light', 'name': 'Сыр творожный лёгкий', 'kcal': 250, 'group': 'Молочные продукты'},
    {'id': 'buttermilk', 'name': 'Пахта', 'kcal': 40, 'group': 'Молочные продукты'},
    {'id': 'egg_quail', 'name': 'Яйцо перепелиное', 'kcal': 158, 'group': 'Яйца'},
    {'id': 'egg_boiled', 'name': 'Яйцо варёное', 'kcal': 155, 'group': 'Яйца'},
    {'id': 'oats_flakes', 'name': 'Овсяные хлопья', 'kcal': 366, 'group': 'Крупы и макароны'},
    {'id': 'oats_dry', 'name': 'Овсянка (сухая)', 'kcal': 342, 'group': 'Крупы и макароны'},
    {'id': 'millet_dry', 'name': 'Пшено (сухое)', 'kcal': 348, 'group': 'Крупы и макароны'},
    {'id': 'rice_parboiled_dry', 'name': 'Рис пропаренный (сухой)', 'kcal': 345, 'group': 'Крупы и макароны'},
    {'id': 'pasta_spaghetti', 'name': 'Спагетти (сухие)', 'kcal': 344, 'group': 'Крупы и макароны'},
    {'id': 'pasta_horns', 'name': 'Макароны-рожки (сухие)', 'kcal': 344, 'group': 'Крупы и макароны'},
    {'id': 'noodles_instant', 'name': 'Лапша быстрого приготовления', 'kcal': 436, 'group': 'Крупы и макароны'},
    {'id': 'peas_split_dry', 'name': 'Горох колотый (сухой)', 'kcal': 298, 'group': 'Крупы и макароны'},
    {'id': 'wheat_groats', 'name': 'Пшеничная крупа (сухая)', 'kcal': 326, 'group': 'Крупы и макароны'},
    {'id': 'muesli', 'name': 'Мюсли', 'kcal': 352, 'group': 'Крупы и макароны'},
    {'id': 'wheat_bran', 'name': 'Отруби пшеничные', 'kcal': 216, 'group': 'Крупы и макароны'},
    {'id': 'corn_grits_dry', 'name': 'Кукурузная крупа (сухая)', 'kcal': 337, 'group': 'Крупы и макароны'},
    {'id': 'rice_wild', 'name': 'Рис дикий (варёный)', 'kcal': 101, 'group': 'Крупы и макароны'},
    {'id': 'buckwheat_green', 'name': 'Гречка зелёная (сухая)', 'kcal': 308, 'group': 'Крупы и макароны'},
    {'id': 'bread_borodino', 'name': 'Хлеб Бородинский', 'kcal': 201, 'group': 'Хлеб и выпечка'},
    {'id': 'bread_baton', 'name': 'Батон нарезной', 'kcal': 262, 'group': 'Хлеб и выпечка'},
    {'id': 'toast', 'name': 'Тосты', 'kcal': 313, 'group': 'Хлеб и выпечка'},
    {'id': 'sushki', 'name': 'Сушки', 'kcal': 330, 'group': 'Хлеб и выпечка'},
    {'id': 'baranki', 'name': 'Баранки', 'kcal': 336, 'group': 'Хлеб и выпечка'},
    {'id': 'vatrushka', 'name': 'Ватрушка с творогом', 'kcal': 290, 'group': 'Хлеб и выпечка'},
    {'id': 'pirozhok_cabbage', 'name': 'Пирожок с капустой', 'kcal': 220, 'group': 'Хлеб и выпечка'},
    {'id': 'pirozhok_meat', 'name': 'Пирожок с мясом', 'kcal': 275, 'group': 'Хлеб и выпечка'},
    {'id': 'croutons', 'name': 'Сухарики', 'kcal': 390, 'group': 'Хлеб и выпечка'},
    {'id': 'potato_fried', 'name': 'Картофель жареный', 'kcal': 192, 'group': 'Овощи'},
    {'id': 'onion_fried', 'name': 'Лук жареный', 'kcal': 132, 'group': 'Овощи'},
    {'id': 'cabbage_pickled', 'name': 'Капуста маринованная', 'kcal': 22, 'group': 'Овощи'},
    {'id': 'eggplant_caviar', 'name': 'Баклажанная икра', 'kcal': 146, 'group': 'Овощи'},
    {'id': 'squash_caviar', 'name': 'Кабачковая икра', 'kcal': 105, 'group': 'Овощи'},
    {'id': 'radish_black', 'name': 'Редька чёрная', 'kcal': 35, 'group': 'Овощи'},
    {'id': 'frozen_broccoli', 'name': 'Брокколи замороженная', 'kcal': 34, 'group': 'Овощи'},
    {'id': 'frozen_peas', 'name': 'Горошек замороженный', 'kcal': 81, 'group': 'Овощи'},
    {'id': 'frozen_mix', 'name': 'Овощная смесь замороженная', 'kcal': 50, 'group': 'Овощи'},
    {'id': 'tomato_paste_diluted', 'name': 'Томатный соус', 'kcal': 50, 'group': 'Овощи'},
    {'id': 'cabbage_savoy', 'name': 'Капуста савойская', 'kcal': 27, 'group': 'Овощи'},
    {'id': 'cabbage_beijing', 'name': 'Капуста пекинская', 'kcal': 16, 'group': 'Овощи'},
    {'id': 'tomato_dried', 'name': 'Томаты сушёные', 'kcal': 258, 'group': 'Овощи'},
    {'id': 'mushrooms_pickle', 'name': 'Грибы маринованные', 'kcal': 22, 'group': 'Овощи'},
    {'id': 'mushrooms_oyster', 'name': 'Грибы вешенки', 'kcal': 38, 'group': 'Овощи'},
    {'id': 'apple_dried', 'name': 'Яблоки сушёные', 'kcal': 253, 'group': 'Фрукты и ягоды'},
    {'id': 'sea_buckthorn', 'name': 'Облепиха', 'kcal': 82, 'group': 'Фрукты и ягоды'},
    {'id': 'lingonberry', 'name': 'Брусника', 'kcal': 46, 'group': 'Фрукты и ягоды'},
    {'id': 'rowan', 'name': 'Рябина', 'kcal': 51, 'group': 'Фрукты и ягоды'},
    {'id': 'dried_cranberry', 'name': 'Клюква сушёная', 'kcal': 308, 'group': 'Фрукты и ягоды'},
    {'id': 'banana_dried', 'name': 'Банан сушёный', 'kcal': 346, 'group': 'Фрукты и ягоды'},
    {'id': 'persimmon', 'name': 'Хурма', 'kcal': 67, 'group': 'Фрукты и ягоды'},
    {'id': 'nectarine', 'name': 'Нектарин', 'kcal': 44, 'group': 'Фрукты и ягоды'},
    {'id': 'peas_canned', 'name': 'Горошек консервированный', 'kcal': 58, 'group': 'Бобовые'},
    {'id': 'corn_canned', 'name': 'Кукуруза консервированная', 'kcal': 58, 'group': 'Бобовые'},
    {'id': 'beans_canned', 'name': 'Фасоль консервированная', 'kcal': 99, 'group': 'Бобовые'},
    {'id': 'soybeans_boiled', 'name': 'Соя (варёная)', 'kcal': 173, 'group': 'Бобовые'},
    {'id': 'mung_beans', 'name': 'Маш (варёный)', 'kcal': 105, 'group': 'Бобовые'},
    {'id': 'ghee', 'name': 'Масло топлёное', 'kcal': 869, 'group': 'Масла и соусы'},
    {'id': 'bouillon_cube', 'name': 'Бульонный кубик', 'kcal': 260, 'group': 'Масла и соусы'},
    {'id': 'bouillon_chicken', 'name': 'Бульон куриный', 'kcal': 15, 'group': 'Масла и соусы'},
    {'id': 'salad_dressing', 'name': 'Заправка для салата', 'kcal': 430, 'group': 'Масла и соусы'},
    {'id': 'mustard_dijon', 'name': 'Горчица дижонская', 'kcal': 120, 'group': 'Масла и соусы'},
    {'id': 'vinegar_apple', 'name': 'Уксус яблочный', 'kcal': 21, 'group': 'Масла и соусы'},
    {'id': 'sauce_soy_garlic', 'name': 'Соус чесночный', 'kcal': 180, 'group': 'Масла и соусы'},
    {'id': 'coffee_milk', 'name': 'Кофе с молоком', 'kcal': 58, 'group': 'Напитки'},
    {'id': 'tea_green', 'name': 'Чай зелёный (без сахара)', 'kcal': 1, 'group': 'Напитки'},
    {'id': 'juice_tomato', 'name': 'Сок томатный', 'kcal': 21, 'group': 'Напитки'},
    {'id': 'juice_grape', 'name': 'Сок виноградный', 'kcal': 54, 'group': 'Напитки'},
    {'id': 'juice_multifruit', 'name': 'Сок мультифрукт', 'kcal': 48, 'group': 'Напитки'},
    {'id': 'milkshake', 'name': 'Молочный коктейль', 'kcal': 85, 'group': 'Напитки'},
    {'id': 'cappuccino', 'name': 'Капучино (без сахара)', 'kcal': 45, 'group': 'Напитки'},
    {'id': 'latte', 'name': 'Латте (без сахара)', 'kcal': 56, 'group': 'Напитки'},
    {'id': 'sugar_brown', 'name': 'Сахар коричневый', 'kcal': 380, 'group': 'Сладости'},
    {'id': 'sugar_powder', 'name': 'Сахарная пудра', 'kcal': 389, 'group': 'Сладости'},
    {'id': 'condensed_boiled', 'name': 'Сгущёнка варёная', 'kcal': 315, 'group': 'Сладости'},
    {'id': 'jam_strawberry', 'name': 'Варенье клубничное', 'kcal': 278, 'group': 'Сладости'},
    {'id': 'marmalade', 'name': 'Мармелад', 'kcal': 266, 'group': 'Сладости'},
    {'id': 'chocolate_nuts', 'name': 'Шоколад с орехами', 'kcal': 550, 'group': 'Сладости'},
    {'id': 'flour_whole', 'name': 'Мука цельнозерновая', 'kcal': 320, 'group': 'Прочее'},
    {'id': 'soda_food', 'name': 'Пищевая сода', 'kcal': 0, 'group': 'Прочее'},
    {'id': 'bay_leaf', 'name': 'Лавровый лист', 'kcal': 313, 'group': 'Прочее'},
    {'id': 'oregano_dried', 'name': 'Орегано сушёный', 'kcal': 265, 'group': 'Прочее'},
    {'id': 'dill_dried', 'name': 'Укроп сушёный', 'kcal': 253, 'group': 'Прочее'},
    {'id': 'nutmeg', 'name': 'Мускатный орех', 'kcal': 525, 'group': 'Прочее'},
    {'id': 'cloves', 'name': 'Гвоздика', 'kcal': 274, 'group': 'Прочее'},
    {'id': 'curry_powder', 'name': 'Карри (порошок)', 'kcal': 325, 'group': 'Прочее'},
    {'id': 'quinoa_dry', 'name': 'Киноа (сухая)', 'kcal': 368, 'group': 'Деликатесы и редкое'},
    {'id': 'tempeh', 'name': 'Темпе', 'kcal': 192, 'group': 'Деликатесы и редкое'},
    {'id': 'miso_paste', 'name': 'Паста мисо', 'kcal': 199, 'group': 'Деликатесы и редкое'},
    {'id': 'kimchi', 'name': 'Кимчи', 'kcal': 15, 'group': 'Деликатесы и редкое'},
    {'id': 'wasabi', 'name': 'Васаби', 'kcal': 109, 'group': 'Деликатесы и редкое'},
    {'id': 'dragon_fruit', 'name': 'Питахайя', 'kcal': 60, 'group': 'Деликатесы и редкое'},
    {'id': 'lychee', 'name': 'Личи', 'kcal': 66, 'group': 'Деликатесы и редкое'},
    {'id': 'passion_fruit', 'name': 'Маракуйя', 'kcal': 97, 'group': 'Деликатесы и редкое'},
    {'id': 'durian', 'name': 'Дуриан', 'kcal': 147, 'group': 'Деликатесы и редкое'},
    {'id': 'jackfruit', 'name': 'Джекфрут', 'kcal': 95, 'group': 'Деликатесы и редкое'},
    {'id': 'matcha_powder', 'name': 'Матча (порошок)', 'kcal': 324, 'group': 'Деликатесы и редкое'},
    {'id': 'protein_bar', 'name': 'Батончик протеиновый', 'kcal': 350, 'group': 'Деликатесы и редкое'},
    {'id': 'energy_drink', 'name': 'Энергетик', 'kcal': 45, 'group': 'Деликатесы и редкое'},
    {'id': 'truffle_oil', 'name': 'Масло трюфельное', 'kcal': 884, 'group': 'Деликатесы и редкое'},
    {'id': 'caviar_black', 'name': 'Икра чёрная', 'kcal': 264, 'group': 'Деликатесы и редкое'},
    {'id': 'foie_gras', 'name': 'Фуа-гра', 'kcal': 462, 'group': 'Деликатесы и редкое'},
    {'id': 'escargot', 'name': 'Улитки', 'kcal': 90, 'group': 'Деликатесы и редкое'},
    {'id': 'venison', 'name': 'Оленина', 'kcal': 158, 'group': 'Деликатесы и редкое'},
    {'id': 'ostrich', 'name': 'Страус (мясо)', 'kcal': 145, 'group': 'Деликатесы и редкое'},
    {'id': 'camel_milk', 'name': 'Верблюжье молоко', 'kcal': 52, 'group': 'Деликатесы и редкое'},
]

# Готовые рецепты: product_id и граммы на порцию (ориентир для демо-калькулятора).
DISH_CALCULATOR_RECIPES: list[dict] = [
    {
        'id': 'borscht_home',
        'name': 'Борщ домашний',
        'ingredients': [
            {'product_id': 'beef', 'grams': 80},
            {'product_id': 'beet', 'grams': 100},
            {'product_id': 'potato', 'grams': 120},
            {'product_id': 'cabbage', 'grams': 80},
            {'product_id': 'carrot', 'grams': 50},
            {'product_id': 'onion', 'grams': 40},
            {'product_id': 'tomato_paste', 'grams': 20},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
    {
        'id': 'chicken_noodle_soup',
        'name': 'Суп куриный с лапшой',
        'ingredients': [
            {'product_id': 'chicken_breast', 'grams': 120},
            {'product_id': 'pasta_dry', 'grams': 50},
            {'product_id': 'carrot', 'grams': 60},
            {'product_id': 'potato', 'grams': 100},
            {'product_id': 'onion', 'grams': 40},
        ],
    },
    {
        'id': 'shchi',
        'name': 'Щи из свежей капусты',
        'ingredients': [
            {'product_id': 'cabbage', 'grams': 150},
            {'product_id': 'potato', 'grams': 100},
            {'product_id': 'carrot', 'grams': 50},
            {'product_id': 'onion', 'grams': 40},
            {'product_id': 'tomato_paste', 'grams': 15},
            {'product_id': 'sunflower_oil', 'grams': 10},
        ],
    },
    {
        'id': 'solyanka',
        'name': 'Солянка сборная',
        'ingredients': [
            {'product_id': 'sausage_doctor', 'grams': 60},
            {'product_id': 'sausage_smoked', 'grams': 40},
            {'product_id': 'beef', 'grams': 70},
            {'product_id': 'cucumber', 'grams': 40},
            {'product_id': 'tomato', 'grams': 80},
            {'product_id': 'onion', 'grams': 50},
            {'product_id': 'olive_oil', 'grams': 10},
        ],
    },
    {
        'id': 'salad_olivier',
        'name': 'Салат Оливье',
        'ingredients': [
            {'product_id': 'potato_boiled', 'grams': 150},
            {'product_id': 'carrot', 'grams': 80},
            {'product_id': 'egg', 'grams': 100},
            {'product_id': 'cucumber', 'grams': 100},
            {'product_id': 'green_peas', 'grams': 80},
            {'product_id': 'sausage_doctor', 'grams': 120},
            {'product_id': 'mayo_67', 'grams': 80},
        ],
    },
    {
        'id': 'salad_caesar',
        'name': 'Салат Цезарь',
        'ingredients': [
            {'product_id': 'chicken_breast', 'grams': 150},
            {'product_id': 'cabbage', 'grams': 100},
            {'product_id': 'cheese_hard', 'grams': 40},
            {'product_id': 'bread_white', 'grams': 30},
            {'product_id': 'tomato', 'grams': 80},
            {'product_id': 'mayo_light', 'grams': 40},
        ],
    },
    {
        'id': 'salad_greek',
        'name': 'Салат греческий',
        'ingredients': [
            {'product_id': 'cucumber', 'grams': 120},
            {'product_id': 'tomato', 'grams': 150},
            {'product_id': 'pepper', 'grams': 80},
            {'product_id': 'onion', 'grams': 40},
            {'product_id': 'cheese_feta', 'grams': 80},
            {'product_id': 'olive_oil', 'grams': 20},
        ],
    },
    {
        'id': 'salad_vinegret',
        'name': 'Салат винегрет',
        'ingredients': [
            {'product_id': 'beet', 'grams': 120},
            {'product_id': 'potato_boiled', 'grams': 120},
            {'product_id': 'carrot', 'grams': 80},
            {'product_id': 'cucumber', 'grams': 80},
            {'product_id': 'green_peas', 'grams': 60},
            {'product_id': 'sunflower_oil', 'grams': 25},
        ],
    },
    {
        'id': 'salad_fresh',
        'name': 'Салат из свежих овощей',
        'ingredients': [
            {'product_id': 'cucumber', 'grams': 150},
            {'product_id': 'tomato', 'grams': 150},
            {'product_id': 'pepper', 'grams': 80},
            {'product_id': 'onion', 'grams': 30},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
    {
        'id': 'pelmeni',
        'name': 'Пельмени домашние',
        'ingredients': [
            {'product_id': 'minced_mixed', 'grams': 200},
            {'product_id': 'onion', 'grams': 40},
            {'product_id': 'egg', 'grams': 50},
            {'product_id': 'pasta_dry', 'grams': 120},
            {'product_id': 'butter', 'grams': 20},
        ],
    },
    {
        'id': 'buckwheat_chicken',
        'name': 'Гречка с курицей',
        'ingredients': [
            {'product_id': 'buckwheat_dry', 'grams': 80},
            {'product_id': 'chicken_breast', 'grams': 150},
            {'product_id': 'onion', 'grams': 50},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
    {
        'id': 'plov',
        'name': 'Плов с говядиной',
        'ingredients': [
            {'product_id': 'rice_dry', 'grams': 100},
            {'product_id': 'beef', 'grams': 150},
            {'product_id': 'carrot', 'grams': 100},
            {'product_id': 'onion', 'grams': 80},
            {'product_id': 'sunflower_oil', 'grams': 30},
            {'product_id': 'garlic', 'grams': 10},
        ],
    },
    {
        'id': 'mashed_potato',
        'name': 'Картофельное пюре',
        'ingredients': [
            {'product_id': 'potato', 'grams': 300},
            {'product_id': 'milk_25', 'grams': 100},
            {'product_id': 'butter', 'grams': 30},
        ],
    },
    {
        'id': 'omelette',
        'name': 'Омлет с молоком',
        'ingredients': [
            {'product_id': 'egg', 'grams': 150},
            {'product_id': 'milk_25', 'grams': 50},
            {'product_id': 'butter', 'grams': 15},
        ],
    },
    {
        'id': 'fried_eggs',
        'name': 'Яичница',
        'ingredients': [
            {'product_id': 'egg', 'grams': 120},
            {'product_id': 'sunflower_oil', 'grams': 10},
        ],
    },
    {
        'id': 'pancakes',
        'name': 'Блины на молоке',
        'ingredients': [
            {'product_id': 'milk_25', 'grams': 250},
            {'product_id': 'egg', 'grams': 100},
            {'product_id': 'sugar', 'grams': 20},
            {'product_id': 'sunflower_oil', 'grams': 20},
        ],
    },
    {
        'id': 'oatmeal_honey',
        'name': 'Овсяная каша с мёдом',
        'ingredients': [
            {'product_id': 'oatmeal', 'grams': 200},
            {'product_id': 'milk_25', 'grams': 150},
            {'product_id': 'honey', 'grams': 20},
        ],
    },
    {
        'id': 'pasta_navy',
        'name': 'Макароны по-флотски',
        'ingredients': [
            {'product_id': 'pasta_dry', 'grams': 100},
            {'product_id': 'minced_beef', 'grams': 150},
            {'product_id': 'onion', 'grams': 60},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
    {
        'id': 'cutlets_potato',
        'name': 'Котлеты с картофелем',
        'ingredients': [
            {'product_id': 'minced_mixed', 'grams': 200},
            {'product_id': 'potato_boiled', 'grams': 200},
            {'product_id': 'egg', 'grams': 50},
            {'product_id': 'bread_white', 'grams': 30},
            {'product_id': 'sunflower_oil', 'grams': 20},
        ],
    },
    {
        'id': 'pork_stew',
        'name': 'Жаркое из свинины',
        'ingredients': [
            {'product_id': 'pork', 'grams': 200},
            {'product_id': 'potato', 'grams': 250},
            {'product_id': 'carrot', 'grams': 80},
            {'product_id': 'onion', 'grams': 60},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
    {
        'id': 'goulash',
        'name': 'Гуляш с гарниром',
        'ingredients': [
            {'product_id': 'beef', 'grams': 180},
            {'product_id': 'onion', 'grams': 80},
            {'product_id': 'tomato_paste', 'grams': 25},
            {'product_id': 'buckwheat_dry', 'grams': 80},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
    {
        'id': 'fried_fish',
        'name': 'Рыба жареная с лимоном',
        'ingredients': [
            {'product_id': 'cod', 'grams': 200},
            {'product_id': 'sunflower_oil', 'grams': 20},
            {'product_id': 'lemon', 'grams': 30},
        ],
    },
    {
        'id': 'kharcho',
        'name': 'Харчо',
        'ingredients': [
            {'product_id': 'beef', 'grams': 120},
            {'product_id': 'rice_dry', 'grams': 60},
            {'product_id': 'tomato', 'grams': 100},
            {'product_id': 'onion', 'grams': 60},
            {'product_id': 'garlic', 'grams': 10},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
    {
        'id': 'cottage_casserole',
        'name': 'Творожная запеканка',
        'ingredients': [
            {'product_id': 'cottage_5', 'grams': 300},
            {'product_id': 'egg', 'grams': 100},
            {'product_id': 'sugar', 'grams': 40},
            {'product_id': 'sour_cream_20', 'grams': 50},
        ],
    },
    {
        'id': 'syrniki',
        'name': 'Сырники',
        'ingredients': [
            {'product_id': 'cottage_5', 'grams': 250},
            {'product_id': 'egg', 'grams': 50},
            {'product_id': 'sugar', 'grams': 30},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
    {
        'id': 'pizza_home',
        'name': 'Пицца домашняя',
        'ingredients': [
            {'product_id': 'bread_whole', 'grams': 120},
            {'product_id': 'cheese_mozzarella', 'grams': 100},
            {'product_id': 'tomato', 'grams': 100},
            {'product_id': 'sausage_servelat', 'grams': 60},
            {'product_id': 'olive_oil', 'grams': 10},
        ],
    },
    {
        'id': 'sandwich_butter_cheese',
        'name': 'Бутерброд с маслом и сыром',
        'ingredients': [
            {'product_id': 'bread_white', 'grams': 60},
            {'product_id': 'butter', 'grams': 15},
            {'product_id': 'cheese_hard', 'grams': 30},
        ],
    },
    {
        'id': 'sandwich_sausage',
        'name': 'Сэндвич с колбасой',
        'ingredients': [
            {'product_id': 'bread_white', 'grams': 80},
            {'product_id': 'sausage_doctor', 'grams': 60},
            {'product_id': 'cheese_hard', 'grams': 25},
            {'product_id': 'tomato', 'grams': 40},
            {'product_id': 'butter', 'grams': 10},
        ],
    },
    {
        'id': 'chicken_wings_baked',
        'name': 'Куриные крылышки запечённые',
        'ingredients': [
            {'product_id': 'chicken_wing', 'grams': 300},
            {'product_id': 'potato', 'grams': 200},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
    {
        'id': 'rice_vegetables',
        'name': 'Рис с овощами',
        'ingredients': [
            {'product_id': 'rice_dry', 'grams': 80},
            {'product_id': 'carrot', 'grams': 80},
            {'product_id': 'pepper', 'grams': 80},
            {'product_id': 'green_peas', 'grams': 60},
            {'product_id': 'sunflower_oil', 'grams': 15},
        ],
    },
]
